### ISSUE TITLE
New accessor for peptide ranges via AAStringSet

### ISSUE THREAD

**Issue by baderd** [ComputationalProteomicsUnit/Pbase#24]
Dear Mr Gatto and Mr Gibb,

I do not know whether this is the right way to approach you, so I beg your pardon if not. 

I discovered your package Pbase here and wanted to do the following:
Convert peptide AA sequences from a known gene to GRanges object with DNA coordinates (mapToGenome). This would be my start fasta file peptides.fa (Note the IDs provided here are already HGNC symbols.)
<pre>
>sp|SLC12A2
AAAAAAAAAAAAAAAGAGAGAK
>sp|PABPN1
AAAAAAAAAAGAAGGR
>sp|PHOX2B
AAAAAAAAAK
>sp|SGCB
AAAAAAAAEQQSSNGPVK
>sp|SLC15A4
AAAAAAAAGAFAGR
</pre>

It would be great, if you could add something similar to the function "addIdentificationData" that allows to add peptide information like above, e.g. as AAStringSet and converts it to ranges of the corresponding genes inside a "Proteins" object. So to say a "addPeptideFragments" function. 

Thanks for your help! I am looking forward to all further developments!

Best,
Daniel

**Comment by sgibb** [comment]
Dear Daniel,

thanks for your feature request. Just for clarification: You suggest a function `addPeptideFragments` that takes a fasta file with peptides as input and converts them to the corresponding ranges inside the Proteins object.
Does the fasta files have a Uniprot accession number? Otherwise we have to find the peptides inside the proteins via `grep` or something similar.

Best wishes,

Sebastian

**Comment by baderd** [comment]
Dear Mr Gibb,

You got me right. The peptide fasta file should have IDs. I put HGNC gene names, but I agree that Uniprot accession numbers make most sense. My motivation for starting this issue was to avoid the <code>grep</code> myself, since I thought you might have this already implemented in the <code>addIdentificationData<code> function.

Best,
Daniel

**Comment by lgatto** [comment]
A few points, here. 

- We would need a way to match the peptide and protein identifiers. These would need to be UniProt identifiers. 

- Rather than `grep`, it would be better to align peptide to their id-matched protein. These alignment functions are readily available in `Biostrings`. 
 
The best way here would be to have a peptide `AAStringSet` that contains the matching protein identifiers in `mcols` and then use existing infrastructure to align and extract coordinates.

**Comment by sgibb** [comment]
@baderd is it possible to use a fasta file with Uniprot identifiers?

@lgatto I am not sure that an alignment is necessary. Without any testing I would assume that NW or SW alignment are slower than a `grepexpr` or `Biostrings::matchPattern` approach. IMHO there should be no need to handle gaps and mismatches in finding a peptide sequence in an unmutated protein, or?

**Comment by baderd** [comment]
Yes, Uniprot IDs are good. In my case, the peptides originate from a MassSpec experiment, they should be substrings of the whole protein.

**Comment by lgatto** [comment]
> @lgatto I am not sure that an alignment is necessary. Without any testing I would assume that NW or SW alignment are slower than a grepexpr or Biostrings::matchPattern approach. IMHO there should be no need to handle gaps and mismatches in finding a peptide sequence in an unmutated protein, or?

Maybe not for this specific use case, but I'm thinking about cases where there are insertions/deletions/mutations. `Biostrings::matchPattern` is actually fine, there is no explicit need for alignment.

**Comment by sgibb** [comment]
@lgatto I tried to merge the github version to bioc svn using http://bioconductor.org/developers/how-to/git-mirrors/ but there are a lot of strange merge conflicts after running `git merge master --log`. Did you do something on svn only (without publishing on github)?

**Comment by lgatto** [comment]
> Did you do something on svn only (without publishing on github)?

No, not that I can think of. There are every now and again such issues, but I don't know why. I'll have a look.

**Comment by lgatto** [comment]
> ------------------------------------------------------------------------
> r113044 | hpages@fhcrc.org | 2016-01-29 01:22:03 +0000 (Fri, 29 Jan 2016) | 3 lines
> 
> elementLengths was renamed -> elementNROWS in S4Vectors (new name reflects TRUE
> semantic, old name will be deprecated soon)
> 
> ------------------------------------------------------------------------
> r109592 | d.tenenbaum | 2015-10-13 20:59:53 +0100 (Tue, 13 Oct 2015) | 2 lines
> 
> Bumped version number of all packages after creation of 3.2 branch.
> 
> ------------------------------------------------------------------------
> r109589 | d.tenenbaum | 2015-10-13 20:36:05 +0100 (Tue, 13 Oct 2015) | 2 lines
> 
> Bumped versions of all packages prior to creating 3.2 branch.
>

**Comment by lgatto** [comment]
Merged Bioc commit r113044 into master, fixed version and committed all to Bioc. Bumped version to 0.11.3. I am closing this issue, feel free to re-open if necessary.

**Comment by sgibb** [comment]
@lgatto thanks for doing the merge. It doesn't look very difficult now. I had a conflict in nearly every file (even DESCRIPTION and NEWS). I think I have to change my workflow and always sync with bioc before starting any coding.

**Comment by lgatto** [comment]
One thing that comes handy is
```
git merge master -X [theirs|ours] --log
```
