### ISSUE TITLE
Pbase roadmap to version 1.0.0: changes in Proteins

### ISSUE THREAD

**Issue by jotsetung** [ComputationalProteomicsUnit/Pbase#32]
### Changes in `Proteins` object to resemble more `GRanges`

This is more matter of discussion - it contains mostly ideas for changes I propose:
+ [ ] Allow redundant `seqnames` for `Proteins` objects (see issue #28).
+ [ ] Link `names` method to `seqnames`.

**Comment by sgibb** [comment]
I will do this.
