### ISSUE TITLE
New 1.0.0 Project and how to keep track of changes, ideas etc

### ISSUE THREAD

**Issue by jotsetung** [ComputationalProteomicsUnit/Pbase#33]
I've created now a project to keep track of changes, ideas, todos and notes for version 1.0.0 (thanks to @sgibb ). I'm not entirely sure whether I've done it cleverly - please change to your needs.
I believe we still need to use (lots of) issues to be able to discuss proposals for changes, but can use the 1.0.0 project to organize and keep track of these.

**Comment by sgibb** [comment]
I also added a milestone `1.0.0` to allow easier filtering of the issue list.
