### ISSUE TITLE
No Uniprot ID support yet for ensembl methods

### ISSUE THREAD

**Issue by jotsetung** [ComputationalProteomicsUnit/Pbase#35]
Due to the 1:n mapping between Ensembl _protein_id_ and Uniprot IDs in the Ensembl database functionality using Uniprot IDs is currently disabled in `Proteins,EnsDb` method and `mapToGenome,Proteins,EnsDb` methods.

For `Proteins,EnsDb` a solution to this could be that proteins are replicated for each `uniprot_id`, but this would require that `Proteins` supports redundant `seqnames` (see issue #28).

**Comment by lgatto** [comment]
I am fine with dropping the unique `seqnames` requirement.

**Comment by sgibb** [comment]
me too

**Comment by jotsetung** [comment]
OK, `mapToGenome,Proteins,EnsDb` supports now also Uniprot IDs to search for matching transcripts. Since a protein with the same Uniprot ID can be mapped to (encoded by) several transcripts the method internally selects the transcript which CDS length best matches the protein sequence length.

Will add an example to the `Pbase-with-ensembldb.Rmd` vignette.

**Comment by jotsetung** [comment]
Actually, I was wrong, there is no 1:n mapping between (Ensembl) `protein_id` and `uniprot_id`, but n:1 between `protein_id` and `uniprot_id`. This means, since there is a 1:1 mapping between `protein_id` and (Ensembl) `tx_id` there is also an n:1 between `tx_id` to `uniprot_id`. Since I fixed the selection of the _best_ transcript for a Uniprot ID as described above, there _should_ be full Uniprot ID now.

**Comment by jotsetung** [comment]
Again wrong - in reality the mapping is n:m between `protein_id` and `uniprot_id`: _ENSP00000338157_ is annotated to _Q05516_ and _A0A024R3C6_. So, I'll have to fix also the `Proteins,EnsDb` method accordingly.

**Comment by jotsetung** [comment]
OK, I'll have to check whether I could get some more information about the annotated Uniprot IDs from Ensembl.

**Comment by jotsetung** [comment]
Looking into the available attributes I found only the type of the mapping method by which Uniprot IDs are assigned to Uniprot IDs. I'll also add that to the _uniprot_ table - eventually it'll do (see also issue https://github.com/jotsetung/ensembldb/issues/29).

**Comment by jotsetung** [comment]
Catching up again - `mapToGenome,Proteins,EnsDb` works with Uniprot IDs:
```{r}
library(Pbase)
library(EnsDb.Hsapiens.v86)
edb <- EnsDb.Hsapiens.v86

## Map the Proteins to the genome using the Uniprot IDs.
data(p)
res_3 <- mapToGenome(p, edb, idType = "uniprot_id")

## Compare with what was retrieved by Biomart.
## NOTE: this does only work with Ensembl 86!!!
library("biomaRt")
library(testthat)
ens <- useMart("ensembl", "hsapiens_gene_ensembl")
grl <- etrid2grl(acols(p)$ENST, ens)
all.equal(names(grl), acols(p)$ENST, check.attributes=FALSE)

pcgrl <- proteinCoding(grl)
res <- mapToGenome(p[5], pcgrl[5])
expect_equal(start(res[[1]]), start(res_3[[5]]))
expect_equal(end(res[[1]]), end(res_3[[5]]))

```

**Comment by jotsetung** [comment]
Uniprot support is there.
