### ISSUE TITLE
Pbase build failure on bioc devel/release

### ISSUE THREAD

**Issue by sgibb** [ComputationalProteomicsUnit/Pbase#42]
I just got an email from bioc because `Pbase` could not build on the development or release branch:
http://bioconductor.org/checkResults/release/bioc-LATEST/Pbase/
http://bioconductor.org/checkResults/devel/bioc-LATEST/Pbase/

In the release branch the mapping vignette fails (@lgatto could you have a look):
```
Quitting from lines 66-78 (mapping.Rmd) 
Error: processing vignette 'mapping.Rmd' failed with diagnostics:
Invalid attribute(s): uniprot_swissprot 
Please use the function 'listAttributes' to get valid attribute names
Execution halted
```

In the development branch the error seems to be related to `ensembldb` (@jotsetung could you have a look):
```
Error : objects 'ProteinidFilter', 'UniprotidFilter' are not exported by 'namespace:ensembldb'
ERROR: lazy loading failed for package 'Pbase'
```

**Comment by jotsetung** [comment]
I recently (yesterday) fixed the `ensembldb` related stuff, so that's already in github (but not yet in Bioc). Problem is that with the change to store the peptide features in a `DataFrame` (was done back then in December) some things broke.

**Comment by lgatto** [comment]
I am looking into this now.

**Comment by lgatto** [comment]
@jotsetung - can you help with this
```
No methods found in "GenomicAlignments" for requests: pmapFromTranscripts
Error: package or namespace load failed for 'Gviz':
 object 'GRangesFilter' is not exported by 'namespace:ensembldb'
Error : package 'Gviz' could not be loaded
ERROR: lazy loading failed for package 'Pbase'
* removing '/home/lg390/dev/00_github/Pbase.Rcheck/Pbase'
```

**Comment by lgatto** [comment]
Note that I just updated all my packages, but maybe I need to wait for the latest round of changes to become available via `biocLite`?

**Comment by jotsetung** [comment]
You'll need `biovizBase` version 1.23.3 and `ggbio` version 1.23.7. You should get them with
```r
library(BiocInstaller)
biocLite(c("biovizBase", "ggbio"))
```

**Comment by lgatto** [comment]
Thanks

**Comment by lgatto** [comment]
Will have to try again later because I can't access and `ggbio` 1.23.7 is not yet available
```r
> biocLite(c("biovizBase", "ggbio"))
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.5 (BiocInstaller 1.25.3), R Under development (unstable)
  (2017-02-25 r72256).
Installing package(s) ‘biovizBase’, ‘ggbio’
trying URL 'https://bioconductor.org/packages/3.5/bioc/src/contrib/biovizBase_1.23.2.tar.gz'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://bioconductor.org/packages/3.5/bioc/src/contrib/biovizBase_1.23.2.tar.gz'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open URL 'https://bioconductor.org/packages/3.5/bioc/src/contrib/biovizBase_1.23.2.tar.gz': HTTP status was '404 Not Found'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘biovizBase’ failed
trying URL 'https://bioconductor.org/packages/3.5/bioc/src/contrib/ggbio_1.23.6.tar.gz'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://bioconductor.org/packages/3.5/bioc/src/contrib/ggbio_1.23.6.tar.gz'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open URL 'https://bioconductor.org/packages/3.5/bioc/src/contrib/ggbio_1.23.6.tar.gz': HTTP status was '404 Not Found'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘ggbio’ failed
```

**Comment by jotsetung** [comment]
That is indeed strange - I get the newer versions.
Alternatively:
```r
library(devtools)
install_github("jotsetung/biovizBase")
install_github("jotsetung/ggbio")
```

**Comment by lgatto** [comment]
I painfully went through all the errors, but also had to comment some unit test. At this stage, the `mapToGenome` fails with something that shouldn't have worked before, I think, as the protein ranges are empty. This also breaks the vignette.

**Comment by lgatto** [comment]
That is partly resolved now. @jotsetung, is to be expected?
```r
> ## mapToGenome,Proteins,EnsDb
> library(EnsDb.Hsapiens.v86)
> edb <- EnsDb.Hsapiens.v86
> ## Map the pranges of all proteins in p to the genome providing the proteins'
> mp <- mapToGenome(p, edb, id = "name", idType = "uniprot_id")
Fetch coding region for proteins ...      
OK
Warning message:
In .local(x, genome, ...) :
  From the 9 provided IDs, 1 could not be found in database! Peptide features for those can thus not be mapped.
```
And, in [`.mapToGenome2`](https://github.com/ComputationalProteomicsUnit/Pbase/blob/master/R/coordinate-mapping-methods.R#L173-L180)

```r
    strand_num <- 1
    if (as.character(strand(grObj)[1]) == "-") {
        strand_num <- -1
    }
    ## Ensure exons in grObj are ordered correctly.
    exn_order <- order(start(grObj) * strand_num)
    if (!all(exn_order == 1:length(exn_order)))
        stop("Provided exons in 'grObj' are not ordered by exon index/rank!")
```

when testing `p`, one range fails with 
```r
Warning message:
Mapping failed. Returning an empty range. Last message was: Error in .mapToGenome2(pObj, grObj, pcol, ...): Provided exons in 'grObj' are not ordered by exon index/rank!
```
The exon order and strand are
```r
Browse[2]> exn_order
[1] 5 4 3 2 1
Browse[2]> strand_num
[1] -1
```
Is this not to be expected?

**Comment by jotsetung** [comment]
>  I think, as the protein ranges are empty. This also breaks the vignette.
Really? Wouldn't it be better to support a `Proteins` object without protein ranges? While that would be a simple `AAStringSet` but protein ranges could be added later.

Regarding the `p` object, yes, one range fails, that is to be expected.

Regarding the exon order, that's strange indeed. But I was sure that this function was working.

**Comment by lgatto** [comment]
Builds fine locally now. I have temporarily removed some vignettes, while I finish refactoring. 

@jotsetung - once I feel that the new class/API are mature, I will follow up with the strand and exon order issue.

**Comment by jotsetung** [comment]
OK. I've just added issue #43 that I don't forget that.
