### ISSUE TITLE
Building vignette `Pbase-data.Rmd` fails

### ISSUE THREAD

**Issue by sgibb** [ComputationalProteomicsUnit/Pbase#9]
The build process of Pbase fails on the Bioc servers: http://www.bioconductor.org/checkResults/devel/bioc-LATEST/Pbase/

Error message:

> Quitting from lines 91-93 (Pbase-data.Rmd) 
Error: processing vignette 'Pbase-data.Rmd' failed with diagnostics:
error in evaluating the argument 'value' in selecting a method for function 'setPar': Error: no slot of name "id" for this object of class "GenomeAxisTrack"

**Comment by lgatto** [comment]
Strange. I was able to run this code locally. I then tried to build/check under R-devel after running `biocLite` and got the following

```
This is Pbase version 0.5.2

Error : .onLoad failed in loadNamespace() for 'TxDb.Hsapiens.UCSC.hg19.knownGene', details:
  call: dbGetQuery(conn, SQL)
  error: error in evaluating the argument 'conn' in selecting a method for function 'dbGetQuery': Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object 'dbConn' not found
Calls: ::: -> get

Quitting from lines 38-42 (Pbase-data.Rmd) 
Error: processing vignette 'Pbase-data.Rmd' failed with diagnostics:
package or namespace load failed for 'TxDb.Hsapiens.UCSC.hg19.knownGene'
Execution halted
```

Which I also get if I (re-)install `TxDb.Hsapiens.UCSC.hg19.knownGene`. 

Let's wait a couple of days before following up.

**Comment by sgibb** [comment]
Pbase 0.5.4 builds fine.
